# DATA SETTINGS
data_directory: ../../data/syntheye/pentacam/
transformations:
  resize_dim: 256
  grayscale: 1
  normalize: 1

# GAN I/O SETTINGS
model: msggan
z_dim: 512
output_im_resolution: 256

# TRAINING SETTINGS
epochs: 500
loss_fn: wgan-gp
batch_size: 16
n_disc_updates: 1
lr: 0.003
beta1: 0.0
beta2: 0.99
display_step: 1000
n_samples_to_generate: 5
save_checkpoint_steps: 250
save_tensorboard: 1
save_weights: 1

# EVALUATION SETTINGS
weights_path: checkpoints/data:pentacam_trans:256-1-1_mod:msggan-512-256_tr:2000-relativistic-hinge-16-1-0.003-0.0-0.99/GAN_GEN_SHADOW_500.pth
n_test_samples_to_generate: 50
save_grid: 0