# DATA SETTINGS
data_file: datasets/all_baf_valid_50deg_filtered3.csv
filenames_col: file.path
labels_col: gene
train_classes: classes.txt # provide a list or text file of desired classes to train on
transformations:
  resize_dim: 256
  random_flip: 1
  grayscale: 1
  normalize: 1

# GAN I/O SETTINGS - Required for either training or testing settings
model: cmsgganv2
z_dim: 512
output_im_resolution: 256

# TRAINING SETTINGS
epochs: 1000
loss_fn: wgan-gp
batch_size: 48
n_disc_updates: 1
gen_lr: 0.0003
disc_lr: 0.003
beta1: 0.0
beta2: 0.99
display_step: 300
calc_fid: 1
n_samples_to_generate: 5
save_checkpoint_steps: 50
save_tensorboard: 1
save_weights: 0
parallel: 1
device_ids: [0, 1, 2]

# TESTING SETTINGS
weights_dir: checkpoints/data:all_baf_valid_50deg_filtered3.csvclasses:classes.txt_trans:256-1-1_mod:cmsgganv2-512-256_tr:1000-RAHinge-48-1-0.003-0.003-0.0-0.99/
weights_path: model_ema_state_350.pth
gen_classes: all # provide a list or text file of classes to generate
n_test_samples: 50 # number of test samples per class
evaluate:
  mutual_information: 0
  fid_imagenet: 0
  fid_eye2gene: 1
  class_preds_eye2gene: 0
save_images:
  as_individual: 0
  most_similar: 0
  most_different: 0