# DATA
real_data_file: /home/zchayav/projects/syntheye/datasets/eye2gene_new_filepaths/all_baf_valid_50deg_filtered_train_0_NOREPEATS.csv
synthetic_data_file: /home/zchayav/projects/stylegan2-ada-pytorch/synthetic_datasets/stylegan2_synthetic_-3perclass/generated_examples2.csv
filenames_col: file.path
labels_col: gene
classes: all
transformations:
  resize_dim: 512
  grayscale: 1

# EVALUATION SETTINGS
save_dir: quantitative_results/stylegan2_results/
similarity_check:
  compute: 1
  process_images:
    alpha: 1.0
    beta: 0.0
    filtering:
      kernel:
      size:
    thresholding:
      function:
      size:
  similarity_metric: MSE
  save_most_similar: 1
  save_most_different: 1
quality_check:
  compute: 0
  quality_metric: BRISQUE

#  fid_imagenet: 0
#  fid_eye2gene: 0
#  class_preds_eye2gene: 0
#  save_as:
