# DATA
real_data_file: /home/zchayav/projects/syntheye/euclidean_results/real_wo_repeats.csv
synthetic_data_file: /home/zchayav/projects/syntheye/euclidean_results/synth.csv
filenames_col: file.path
labels_col: gene
classes: all
transformations:
  resize_dim: 299
  grayscale: 3
  normalize: 1

# EVALUATION SETTINGS
save_dir: euclidean_results/real_vs_synthetic/
similarity_check:
  do: 1
  process_images:
    do: 0
    alpha: 1.0
    beta: 0.0
    filtering:
      kernel:
      size:
    thresholding:
      function:
      size:
  dimreduce:
    do: 1
    weights_path: /home/zchayav/projects/syntheye/classifier_training/experiments/best_weights.pth
  similarity_metric: euclidean
  save_most_similar: 1
  save_most_different: 0
quality_check:
  compute: 0
  quality_metric: BRISQUE
