# DATA
real_data_file: /home/zchayav/projects/syntheye/datasets/eye2gene_new_filepaths/all_baf_valid_50deg_filtered_train_0_NOREPEATS.csv
synthetic_data_file: /home/zchayav/projects/syntheye/datasets/eye2gene_new_filepaths/all_baf_valid_50deg_filtered_train_0_NOREPEATS.csv
filenames_col: file.path
labels_col: gene
classes: all
transformations:
  resize_dim: 512
  grayscale: 1
  normalize: 1

# EVALUATION SETTINGS
save_dir: quantitative_results/stylegan2_results/real_vs_real_cosine
similarity_check:
  do: 1
  process_images:
    do: 0
    alpha: 1.0
    beta: 0.0
    filtering:
      kernel:
      size:
    thresholding:
      function:
      size:
  dimreduce:
    do: 1
    latent_size: 1024
    weights_path: /home/zchayav/projects/syntheye/image_encoder/experiment_6/best_weights.pth
  similarity_metric: cosine
  save_most_similar: 1
  save_most_different: 0
quality_check:
  compute: 0
  quality_metric: BRISQUE
