# GAN I/O SETTINGS
model_name: cmsggan1
z_dim: 512
output_im_resolution: 512
generate_randomly: 
weights_dir: checkpoints/cmsggan512_ird_fold1234_experiment2
weights_path: model_ema_state_100.pth
classes: classes.txt # provide a list or text file of classes to generate
class_mapping: classes_mapping.json
n_samples: -1
real_data_path: datasets/eye2gene/all_baf_valid_50deg_filtered_train_0.csv
save_as: CMSGGAN512_rebalanced_dataset/
