# GAN I/O SETTINGS
model_name: cmsggan1
z_dim: 512
output_im_resolution: 512
weights_dir: checkpoints/data:all_baf_valid_50deg_filtered3.csv_classes:classes.txt_trans:512-1-1_mod:cmsggan1-512-512_tr:1000-RAHinge-32-1-0.003-0.003-0.0-0.99
weights_path: model_ema_state_150.pth
classes: ["ABCA4", "USH2A"] # provide a list or text file of classes to generate
class_mapping: class_mapping.json
n_samples: 50
