# DATA SETTINGS
data_file: datasets/faf_dataset_cleaned.csv
filenames_col: file.path
labels_col: gene
train_classes: classes.txt
class_mapping: class_mapping.json
transformations:
  resize_dim: 512
  random_flip: 1
  grayscale: 1
  normalize: 1

# GAN I/O SETTINGS
model: cmsggan1
z_dim: 512
output_im_resolution: 512

# TRAINING SETTINGS
epochs: 1000
loss_fn: RAHinge
batch_size: 32
n_disc_updates: 1
gen_lr: 0.003
disc_lr: 0.003
beta1: 0.0
beta2: 0.99
display_step: 300
calc_fid: 1
n_samples_to_generate: 9
save_checkpoint_steps: 50
save_tensorboard: 1
save_weights: 0
parallel: 1
device_ids: all
